# used by Mise.toml

name: neuronhub

services:
  db:
    image: postgres:18-alpine
    command: >
      postgres -c max_connections=200
               -c shared_buffers=3GB
               -c max_worker_processes=16
               -c max_parallel_workers=8
               -c max_parallel_workers_per_gather=8
               -c max_parallel_maintenance_workers=4
    environment:
      POSTGRES_DB: ${PROJECT_NAME}
      POSTGRES_USER: ${PROJECT_NAME}
      POSTGRES_PASSWORD: ${PROJECT_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username ${PROJECT_NAME}"]
      interval: 5s
      timeout: 5s
    ports:
      - "5432:5432"

volumes:
  postgres_data:
